# Generated by Django 6.0.5 on 2026-05-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raise',
            new_name='Race',
        ),
        migrations.RenameField(
            model_name='guild',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.guild'),
        ),
    ]
